[tool.poetry]
name = "{{ cookiecutter.distribution_name }}"
version = "{{ cookiecutter.version }}"
description = "{{ cookiecutter.description }}"
license = "{{ cookiecutter.license }}"
authors = "{{ cookiecutter.authors }}"
readme = "{{ cookiecutter.readme }}"
keywords = [{{ cookiecutter.keywords }}]

repository = "{{ cookiecutter.repo_url }}"

classifiers = [
    "Development Status :: {{ cookiecutter.dev_status }}",
    "Environment :: Console",
    "Framework :: Pelican",
    "Framework :: Pelican :: Plugins",
    "Intended Audience :: End Users/Desktop",
{%- if cookiecutter.license in ["BSD-2-Clause", "BSD 2-Clause License", "BSD 3-Clause License"] %}
    "License :: OSI Approved :: BSD License",
{%- endif %}
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.urls]
{% for link_name, link_url in cookiecutter.links.items() %}"{{ link_name }}" = "{{ link_url }}"
{% endfor %}
[tool.poetry.dependencies]
python = "{{ cookiecutter.python_version }}"
pelican = "{{ cookiecutter.pelican_version }}"
markdown = {version = "^3.1.1",optional = true}

[tool.poetry.dev-dependencies]
black = {version = "^19.3b0",allows-prereleases = true}
flake8 = "^3.7"
flake8-black = "^0.1.0"
invoke = "^1.3"
isort = "^4.3"
livereload = "^2.6"
markdown = "^3.1.1"
pytest = "^5.0"
pytest-cov = "^2.7"
pytest-django = "^3.5"
pytest-emoji = "^0.2.0"
pytest-pythonpath = "^0.7.3"
pytest-sugar = "^0.9.2"
sphinx_rtd_theme = "^0.4.3"
Werkzeug = "^0.15.5"

[tool.poetry.extras]
markdown = ["markdown"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
